# Generated by Django 4.0.6 on 2022-07-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='des',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
