# Generated by Django 4.0.6 on 2022-08-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestamps',
            new_name='timestamp',
        ),
    ]
