# Generated by Django 4.0.6 on 2022-08-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_timestamps_orderupdate_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='shop/image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
